import { sendMessage } from './runtimeClient.js';
const $ = (id) => document.getElementById(id);
let initialized = false; let timer = null; let page = 1; let taskPage = 1;
const ACTIVE_BATCH_STATUSES = 'SUBMITTED,PROCESSING,PARTIAL_SUCCESS,FAILED,ERROR,INVALID';
const ACTIVE_TASK_STATUSES = 'QUEUED,CLAIMED,SUBMITTED,PROCESSING,FAILED,ERROR,INVALID';
const api = (method, path, data, params) => sendMessage('WQP_VARIANT_API_REQUEST', { request: { method, path, data, params } });
const val = (x) => x === undefined || x === null || x === '' ? '-' : x;
function payload(result) {
    const body = result?.data ?? result;
    return body?.success === false ? (() => { throw new Error(body.detail || body.message || '回测接口返回失败'); })() : (body?.data ?? body);
}
function ensureUi() { const panel = $('backtestPanel'); if (!$('backtestBatches')) { panel.insertAdjacentHTML('beforeend', '<div class="section-title">已提交批次</div><div id="backtestBatches" class="cache-list"></div><div id="backtestBatchPager" class="grid-actions"></div>'); } }
function render() { $('backtestStats').textContent = `待提交 ${val(state.stats.pending)} · 处理中 ${val(state.stats.processing)} · 已完成 ${val(state.stats.completed)} · 失败 ${val(state.stats.failed)}`; $('backtestGroups').innerHTML = state.groups.map(g => `<div class="info-box"><strong>${val(g.language)} / ${val(g.instrument_type || g.instrumentType)} / ${val(g.region)} / Delay ${val(g.delay)}</strong><br>${(g.items || []).length} 条 <button data-group="${g.group_key || g.groupKey || ''}">开始回测</button></div>`).join('') || '暂无待提交变体'; $('backtestBatches').innerHTML = state.batches.map(b => `<div class="info-box"><strong>${val(b.batch_id || b.batchId)}</strong> · ${val(b.status)} · ${val(b.expression_count || b.expressionCount)} 条表达式<br>${val(b.error_message || b.errorMessage)} ${['FAILED','ERROR','PARTIAL_SUCCESS'].includes(b.status) ? `<button data-batch="${b.batch_id || b.batchId}">重试</button>` : ''}</div>`).join('') || '暂无批次'; $('backtestTasks').innerHTML = state.tasks.map(t => `<details class="info-box"><summary>${val(t.id)} · ${val(t.variant_id || t.variantId)} · ${val(t.status)}</summary><div>${val(t.result_alpha_id || t.resultAlphaId)}<br>${val(t.error_message || t.errorMessage || t.result_json || t.resultJson)} ${t.status === 'FAILED' ? `<button data-task="${t.id}">重试</button>` : ''}</div></details>`).join('') || '暂无任务'; }
const state = { stats: {}, groups: [], batches: [], tasks: [] };
async function refresh() { ensureUi(); const keyword = $('backtestKeyword')?.value || ''; const status = $('backtestStatus')?.value || ''; const batchStatus = status || ACTIVE_BATCH_STATUSES; try { const [s, g, b, t] = await Promise.all([api('GET', '/api/variant/backtest/stats'), api('GET', '/api/variant/backtest/groups'), api('GET', '/api/variant/backtest/batches', undefined, { page, size: 20, status: batchStatus }), api('GET', '/api/variant/backtest/tasks', undefined, { page: taskPage, size: 20, status: ACTIVE_TASK_STATUSES, keyword })]); state.stats = payload(s) || {}; state.groups = Array.isArray(payload(g)) ? payload(g) : []; const batches = payload(b) || {}; const tasks = payload(t) || {}; state.batches = (batches.items || []).filter((item) => item.status !== 'COMPLETED').slice(); state.tasks = (tasks.items || []).filter((item) => !['COMPLETED', 'COMPLETE'].includes(item.status)).slice(); state.batchTotal = state.batches.length; state.taskTotal = state.tasks.length; render(); clearInterval(timer); if (Number(state.stats.processing) > 0 || state.tasks.some((item) => ['QUEUED', 'CLAIMED', 'SUBMITTED', 'PROCESSING'].includes(item.status))) timer = setInterval(() => refresh().catch(() => {}), 60000); } catch (error) { $('backtestStats').textContent = `回测数据加载失败：${error.message}`; $('backtestGroups').textContent = '请确认 Java 后端已启动，且 API Base URL 配置正确。'; $('backtestBatches').textContent = ''; $('backtestTasks').textContent = ''; throw error; } }
export async function initBacktestQueuePanel() { ensureUi(); if (!initialized) { initialized = true; $('backtestRefreshBtn').onclick = () => refresh().catch(() => {}); $('backtestKeyword').onchange = () => refresh().catch(() => {}); $('backtestGroups').onclick = async (e) => { const key = e.target.dataset.group; if (key) { await api('POST', '/api/variant/backtest/groups/run', { queue_ids: (state.groups.find(g => String(g.group_key || g.groupKey) === key)?.queue_ids || []) }); await refresh(); } }; $('backtestBatches').onclick = async (e) => { if (e.target.dataset.batch) { await api('POST', `/api/variant/backtest/batches/${encodeURIComponent(e.target.dataset.batch)}/retry`); await refresh(); } }; $('backtestTasks').onclick = async (e) => { if (e.target.dataset.task) { await api('POST', `/api/variant/backtest/tasks/${encodeURIComponent(e.target.dataset.task)}/retry`); await refresh(); } }; } await refresh(); }
